### ISSUE TITLE
Question about the existing GPIOs

### ISSUE THREAD

**Issue by CaiHengrui** [CaiHengrui/BME590L-lab07#3]
https://github.com/CaiHengrui/BME590L-lab07/blob/dd915185d4b02183d09cd4651be26ddf85c678f9/nrf52833dk_nrf52833.overlay#L13-L57

About the first four LEDs, all I need to do is use them directly, rights? And do I need to rewrite the label?
In the dts:
```
	leds {
		compatible = "gpio-leds";
		led0: led_0 {
			gpios = <&gpio0 13 GPIO_ACTIVE_LOW>;
			label = "Green LED 0";
		};
		led1: led_1 {
			gpios = <&gpio0 14 GPIO_ACTIVE_LOW>;
			label = "Green LED 1";
		};
		led2: led_2 {
			gpios = <&gpio0 15 GPIO_ACTIVE_LOW>;
			label = "Green LED 2";
		};
		led3: led_3 {
			gpios = <&gpio0 16 GPIO_ACTIVE_LOW>;
			label = "Green LED 3";
		};
	};
```
like `label = "heartbeat LED"`

**Comment by mlp6** [comment]
You have implemented this as the assignment asked you to.
