### ISSUE TITLE
Question about 'Initialize all LED output pins as GPIO ACTIVE LOW'

### ISSUE THREAD

**Issue by CaiHengrui** [CaiHengrui/BME590L-lab07#5]
https://github.com/CaiHengrui/BME590L-lab07/blob/296dab41d2c42b001343d8f9a48990d974286893/src/main.c#L96-L105

Should I wirte like this `err = gpio_pin_configure_dt(&heartbeat_led, GPIO_ACTIVE_LOW); ` to fulfill the requirement of 'Initialize all LED output pins as GPIO ACTIVE LOW'?

Thanks in advance.

**Comment by mlp6** [comment]
Yep
